### ISSUE TITLE
Copycat policy?

### ISSUE THREAD

**Issue by scosman** [xcomptek/awesome-saas-boilerplates#70]
You added a site the other day (svelte ship). 

This is a fork of my open source https://github.com/CriticalMoments/CMSaasStarter

The author is claiming a ton of places to have created it without attributing the source. They are using a bunch of my copywriting without my permission in their public marketing and docs page. IANAL but their claim of following the licence by including it in a private form (while distributing my content publicly) likely doesn't hold water.

What's your copycat policy (for lack of a better term)?

**Comment by czue** [comment]
Thanks for flagging this and sorry - that sound super frustrating.

I'm not the maintainer but have also been frustrated with the lack of curation and moderation on this list. I have built a directory site based on this repo (https://saasstarters.com/, still a work in progress) to help provide more visibility into the projects listed here.

Anyway, I've gone ahead and [noted this problem here](https://saasstarters.com/starter/svelteship/) so that hopefully at least anyone who finds it via that site will be aware of the problem.

**Comment by smirnov-am** [comment]
I've deleted svelte ship from the list. and added yours

**Comment by scosman** [comment]
Thanks.

FYI: mine was already there (saasstarter.work is the same as the GitHub project). Submitted a PR to avoid the duplicate: https://github.com/smirnov-am/awesome-saas-boilerplates/pull/74
